In [9]:
import torch

A = torch.randn(3,3) # 3행 3열의 표준정규분포따르는 실수들 만들기
print(A)

tensor([[-2.3371, -0.6514,  0.7139],
        [-0.3179,  0.2045, -1.3919],
        [ 0.0484, -0.3460,  0.0498]])


In [10]:
B = torch.rand(3,3) # 0,1 사이 균등분포에서 뽑는것
print(B)

tensor([[0.6238, 0.7388, 0.8720],
        [0.7899, 0.9984, 0.6957],
        [0.0871, 0.0362, 0.4539]])


In [19]:
A = torch.randn(3,3)

print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1))))
print(torch.log10(torch.tensor(10)))
print(torch.round(A))
print(torch.round(A,decimals=2)) #소수 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림
# tensor형만 입력값으로 받을수있다 정수형 불가

tensor([[0.9455, 0.1794, 2.5768],
        [1.3655, 0.2461, 1.3197],
        [1.4473, 0.1071, 0.2799]])
tensor([[0.9724, 0.4236, 1.6052],
        [1.1686, 0.4961, 1.1488],
        [1.2030, 0.3272, 0.5290]])
tensor([[2.5740, 1.1966, 0.0760],
        [3.9178, 0.7818, 3.7423],
        [0.2352, 0.8985, 0.7559]])
tensor([[-0.0561, -1.7179,  0.9465],
        [ 0.3115, -1.4019,  0.2774],
        [ 0.3697, -2.2342, -1.2735]])
tensor(1.0000)
tensor(1.)
tensor([[ 1.,  0., -3.],
        [ 1., -0.,  1.],
        [-1., -0., -0.]])
tensor([[ 0.9500,  0.1800, -2.5800],
        [ 1.3700, -0.2500,  1.3200],
        [-1.4500, -0.1100, -0.2800]])
tensor([[ 0.,  0., -3.],
        [ 1., -1.,  1.],
        [-2., -1., -1.]])
tensor([[ 1.,  1., -2.],
        [ 2., -0.,  2.],
        [-1., -0., -0.]])


In [21]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.;i) <- float임 만약 tensor와 연산하며 tensor로 바꿔줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6) # 연산시 tensor type으로 바뀌는것 확인 

tensor(0.5000)
tensor(0.5000)
tensor(1.0000)
tensor(-1.)


torch.Tensor

In [26]:
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [40]:
A = torch.randn(3,4)
print(A)
print(torch.max(A))
print(torch.max(A,dim=0)) # 열별로 최댓값을 구하고 그인덱스를 출력해준다.
print(torch.max(A,dim=1)) # 행별로 ~
print(torch.argmax(A))
print(torch.argmax(A,dim=0)) # 열별로 가장 큰값의 인덱스
print(torch.argmax(A,dim=1)) # 행별로 가장 큰값의 인덱스

tensor([[-0.7079, -0.0783,  0.5515, -1.4634],
        [ 0.2963, -0.3863, -0.0558, -1.1036],
        [ 0.2162, -1.1267, -0.2225,  0.7633]])
tensor(0.7633)
torch.return_types.max(
values=tensor([ 0.2963, -0.0783,  0.5515,  0.7633]),
indices=tensor([1, 0, 0, 2]))
torch.return_types.max(
values=tensor([0.5515, 0.2963, 0.7633]),
indices=tensor([2, 0, 3]))
tensor(11)
tensor([1, 0, 0, 2])
tensor([2, 0, 3])


In [44]:
print(torch.min(A))
print(torch.min(A,dim=0))
print(torch.min(A,dim=0, keepdims=True)) # keepdims는 차원 유지여부를 물어보는것으로 true인 경우 유지 false인 경우 유지x

tensor(-1.4634)
torch.return_types.min(
values=tensor([-0.7079, -1.1267, -0.2225, -1.4634]),
indices=tensor([0, 2, 2, 0]))
torch.return_types.min(
values=tensor([[-0.7079, -1.1267, -0.2225, -1.4634]]),
indices=tensor([[0, 2, 2, 0]]))


In [46]:
print(torch.min(A,dim=1))
print()
print(torch.min(A,dim=1, keepdims=True))

torch.return_types.min(
values=tensor([-1.4634, -1.1036, -1.1267]),
indices=tensor([3, 3, 1]))

torch.return_types.min(
values=tensor([[-1.4634],
        [-1.1036],
        [-1.1267]]),
indices=tensor([[3],
        [3],
        [1]]))


In [50]:
a = torch.randn(6,1)
print(a)
a_sorted=torch.sort(a,dim=0)
print(a_sorted)

tensor([[ 2.9564],
        [ 0.3167],
        [-0.7659],
        [-1.0313],
        [-1.7351],
        [ 1.0178]])
torch.return_types.sort(
values=tensor([[-1.7351],
        [-1.0313],
        [-0.7659],
        [ 0.3167],
        [ 1.0178],
        [ 2.9564]]),
indices=tensor([[4],
        [3],
        [2],
        [1],
        [5],
        [0]]))


In [49]:
a=torch.randn(6,1)
print(a)
print(a.sort(dim=0))
print(a.sort(dim=0, descending=True))

print(torch.max(a))
print(a.max())
print(torch.abs(a))
print(a.abs())

tensor([[-0.0360],
        [-2.3017],
        [-1.6816],
        [-1.4292],
        [ 0.9858],
        [ 0.5055]])
torch.return_types.sort(
values=tensor([[-2.3017],
        [-1.6816],
        [-1.4292],
        [-0.0360],
        [ 0.5055],
        [ 0.9858]]),
indices=tensor([[1],
        [2],
        [3],
        [0],
        [5],
        [4]]))
torch.return_types.sort(
values=tensor([[ 0.9858],
        [ 0.5055],
        [-0.0360],
        [-1.4292],
        [-1.6816],
        [-2.3017]]),
indices=tensor([[4],
        [5],
        [0],
        [3],
        [2],
        [1]]))
tensor(0.9858)
tensor(0.9858)
tensor([[0.0360],
        [2.3017],
        [1.6816],
        [1.4292],
        [0.9858],
        [0.5055]])
tensor([[0.0360],
        [2.3017],
        [1.6816],
        [1.4292],
        [0.9858],
        [0.5055]])


In [ ]:
A = torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=1))

In [ ]:
print(torch.sum(A, dim=1, keepdims=True))

In [ ]:
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A, dim=1, keepdims=True))
print(torch.std(A)) # standard deviation 표준편차

print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

In [51]:
A = torch.randint(1,5,size=(12,)) # 12차원의 1차원텐서 생성을 의미 뒤에 뭐쓰면 그 크기의 행렬생성
print(A)
print(A.shape)

B = A.reshape(2,2,3) # 2행 3열짜리 행렬 두개생성
print(B)
print(B.ndim) # 3차원(1차원은 벡터 2차원은 행렬 이런게 3차원이라는말)

tensor([1, 1, 3, 4, 2, 1, 3, 2, 2, 2, 1, 4])
torch.Size([12])
tensor([[[1, 1, 3],
         [4, 2, 1]],

        [[3, 2, 2],
         [2, 1, 4]]])
3


In [56]:
A = torch.arange(20,)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # -1은 4행이 되도록 열크기를 맞춰주는것이다.
print(A.reshape(2,5,-1))
print(A.reshape(2,5,-1).shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],

        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]]])
torch.Size([2, 5, 2])
torch.Size([1, 20])


In [57]:
print(A.reshape(1,-1)) # 2차원 행 벡터
print(A.reshape(1,-1).shape)
print(A.reshape(-1,1))
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])
torch.Size([1, 20])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])
torch.Size([20, 1])


In [59]:
# 내적하는법

(1)
a = torch.tensor([1,2,3])
b = torch.tensor([2,2,1])
print(torch.sum(a*b))

(2)
a = a.reshape(3,1)
b = b.reshape(3,1)
print(a.transpose(1,0)@b) # 1번째 demension과 0번쨰 demension은 자리를 바꿔라
print(a.permute(1,0)@b) # permute는 premute(0번쨰에 몇번째 놈 오게할래,1번쨰에 몇번째 놈 오게할래)
print(a.T@b)
print(a.t()@b)

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])


In [88]:
A = torch.randn(4,3,6)
print(A)
print(A.permute(1,2,0))
print(A.permute(1,2,0).shape)

tensor([[[-0.2272, -1.5036, -1.3626,  1.5700, -0.7138,  0.3214],
         [-2.3123,  0.8369,  0.1807,  0.6123,  1.1210,  1.2667],
         [-0.1436,  0.2761, -0.7593,  1.2099,  0.0788,  1.3502]],

        [[ 0.9173,  1.1426,  1.1385, -0.9839,  1.0743, -0.6000],
         [-0.8094,  0.4572,  0.7752,  0.9995,  0.5390, -2.0618],
         [ 0.0124,  0.4422,  1.1406,  0.9049,  0.1001,  1.2981]],

        [[-0.8491,  1.2665, -2.7255, -1.5096,  1.1291,  1.5231],
         [ 1.1734, -0.3097,  0.5176,  1.2934,  0.2204,  0.5771],
         [-1.9702,  2.9639, -1.2475, -2.0716, -1.5370,  1.9141]],

        [[ 0.4992,  1.1394, -0.4287,  0.9141,  1.3526, -1.6670],
         [-0.2494,  0.6325, -0.2640,  0.0387,  0.5431,  0.4728],
         [-1.7117,  1.0436, -0.3731,  1.4986,  1.1582,  0.4073]]])
tensor([[[-0.2272,  0.9173, -0.8491,  0.4992],
         [-1.5036,  1.1426,  1.2665,  1.1394],
         [-1.3626,  1.1385, -2.7255, -0.4287],
         [ 1.5700, -0.9839, -1.5096,  0.9141],
         [-0.7138,  1.07

In [61]:
print(A.transpose(2,1).shape)

torch.Size([4, 6, 3])


In [70]:
# 잘하는 사람들은 간편하게 쓰기위해 축약된 표현도있다.
x = torch.randn(2,3,4,5,6)
#print(x)
#print(x[1,2,:,:,:]) #두 번째 배치의 세 번째 채널만 선택, 나머지는 그대로 유지
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape)
print(x[:,:,:,:,3].shape)
print(x[...,3].shape)
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape)

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [71]:
# conacatenation 중요한 함수

A = torch.ones(3,4)
B = torch.zeros(3,4)
C = torch.vstack([A,B]) # vertical 세로방향으로 쌓는다
D = torch.hstack([A,B]) # horizontal 가로방향으로 쌓는다
E = torch.cat([A,B], dim=0) # 위보다 일반화된 표현으로 각각 dim=0 or dim=1에 따라 세로 가로방향으로 쌓는다.
F = torch.cat([A,B], dim=1)

print(C)
print(D)
print(E)
print(F)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])


In [75]:
# squeeze & unsqueeze

A = torch.randn(1,1,1,3,1,1,1,4,1,1,1) # squeeze => 텐서에서 차원이 1인 축(dim) 을 자동으로 제거해주는 함수야 (축삭뻗음 효과등에 이용해보자)
print(A.shape)
print(A.squeeze().shape) # 1을 쫙 짜서 없앰
print(A.squeeze(dim=(0,2,4,5)).shape) # 지정한것만 없애줌

torch.Size([1, 1, 1, 3, 1, 1, 1, 4, 1, 1, 1])
torch.Size([3, 4])
torch.Size([1, 3, 1, 4, 1, 1, 1])


In [78]:
A = torch.randn(3,4) # 반대로 unsqueeze는 가상의 한 차원을 내가 원한는 위치에 늘려준다.
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape) # 이렇게 해줘도 되지만 차원을 모두 써주어야하는것이 번거로움
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape) # 3행 4열자리 행렬을 깊이 축으로 쌓고싶을때

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [81]:
A = torch.ones(3,4)
B = torch.zeros(3,4)
C = torch.stack([A,B]) # unsqueeze 말고 stack이용 가능 (차원을 추가해서 쌓아줌 때문에 A,B shape이 완전히 일치해야함,concat은 달라도 쌓을 차원 이외 차원만 맞아면됨
print(C)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [82]:
A = torch.tensor([[1,2],[3,4]])
B = A.clone() # B = A 라고만 하면 아예 둘이 같아져 주소까지 같이가져와 하나를 수정하면 하나도 수정이된다 이것을 막기위한것이 clone이다.
B[0,0] = 100

print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


In [84]:
# @연산 추가설명

A = torch.randn(5,7)
B = torch.randn(7,10)
C = A@B
print(C.shape)

torch.Size([5, 10])
tensor([[[ 1.3434,  0.6414,  0.1717,  ..., -0.1191,  1.3875, -0.6356],
         [ 0.1489,  1.1682,  0.4305,  ..., -0.0370,  0.5640, -0.6704],
         [ 0.1503,  0.3065, -1.0850,  ..., -0.3562,  0.2075,  0.0987],
         [-0.5218,  0.2772,  0.2660,  ...,  0.8786,  0.6873, -2.4346],
         [ 0.4492, -0.7259, -1.4403,  ...,  0.1667,  0.7731,  1.2084]],

        [[ 0.4798,  0.0897,  2.3824,  ...,  0.1295, -0.7379,  0.1298],
         [ 0.4073,  1.1303, -0.2699,  ..., -0.6171, -0.2264, -2.7851],
         [-0.0184,  0.7157, -0.1369,  ...,  0.5380, -0.9460, -0.8913],
         [ 0.2043,  0.2492,  0.0485,  ..., -0.2815, -0.5313, -0.0951],
         [ 0.6518,  0.4114, -0.3173,  ...,  0.5940,  0.4076, -0.2678]],

        [[ 0.5224, -0.0691, -0.8189,  ...,  1.9192,  0.6219,  0.6697],
         [-0.4117,  1.5595,  1.2413,  ...,  2.0584,  0.8764, -0.6142],
         [-2.3644,  1.0320, -1.6062,  ..., -1.0257,  2.1567, -0.1458],
         [ 0.3177, -1.0709, -1.1055,  ..., -1.5498,  

In [86]:
A = torch.randn(32,5,7)
B = torch.randn(32,7,10)
C = A@B # 각 행렬이 각 층에 대응 하는 행렬들과 32번 행렬곱된다

print(C.shape)

torch.Size([32, 5, 10])


In [89]:
A = torch.randn(32,5,7)
B = torch.randn(7,10) # 32개의 행렬 각각이 B행렬 한개와 32번 연산후 출력한다
C = A@B

print(C.shape)

torch.Size([32, 5, 10])


In [91]:
# numpy로 바꾸어야 하는 상황도 있을수있는데 numpy와 torch는 서로 변경가능하다
import numpy as np

a = np.array([1,2,3])
b = torch.tensor([1,2,3])
A = torch.tensor(a) # A = torch.from_numpy(a)
B = b.numpy() # B = np.array(b)
print(type(A))
print(type(B))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
