In [7]:
import torch
a = torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
b = torch.tensor([1,2,3.1,4])
print(b.dtype)
print(b)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [8]:
A = torch.tensor([[1,2,3],[3,4,5]])
print(A)
print(A.shape)
print(A.ndim) # number of dimension
print(A.numel()) #number of element

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [12]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])


In [17]:
print(torch.zeros(3,3))
print(torch.arange(3,10,2)) # range와 같은데 tensor로 만들어줌
print(torch.arange(0,1,0.1))
print(torch.linspace(0,1,10)) # linear space (0에서부터 1포함 10개로)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [18]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
c = a+b
print(c)

tensor([5, 7, 9])


In [20]:
A = torch.tensor([[1,2,3],[1,2,3]])
B = torch.tensor([[4,5,6],[1,1,1]])
C = A+B
D = A-B
print(C)
print(D)

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])



In [21]:
print(A*B) # Hadamard product라고 성분끼리의 곱으로 내적 연산은 @이다.
print(A/B)
print(B**2)

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [23]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 트랜스포머의 어텐션에서도 @연산을 사용한다.

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])
