# broadcasting 텐서곱

In [1]:
import torch

# 입력 (B=1로 단순화)
x = torch.tensor([
    [[1., 2., 3., 4., 5.],
     [6., 7., 8., 9., 10.],
     [11.,12.,13.,14.,15.],
     [16.,17.,18.,19.,20.]]
])  # shape: (1,4,5)

# feature weight
w_feature = torch.tensor([10., 100., 1000., 10000., 100000.])  # (5,)

print("=== 원본 x ===")
print(x)

print("\n=== feature weight ===")
print(w_feature)

# broadcasting 곱
out = x * w_feature

print("\n=== 결과 (x * feature_weight) ===")
print(out)

=== 원본 x ===
tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.],
         [16., 17., 18., 19., 20.]]])

=== feature weight ===
tensor([1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05])

=== 결과 (x * feature_weight) ===
tensor([[[1.0000e+01, 2.0000e+02, 3.0000e+03, 4.0000e+04, 5.0000e+05],
         [6.0000e+01, 7.0000e+02, 8.0000e+03, 9.0000e+04, 1.0000e+06],
         [1.1000e+02, 1.2000e+03, 1.3000e+04, 1.4000e+05, 1.5000e+06],
         [1.6000e+02, 1.7000e+03, 1.8000e+04, 1.9000e+05, 2.0000e+06]]])


In [2]:
# position weight
w_position = torch.tensor([1., 10., 100., 1000.])  # (4,)

print("\n=== position weight ===")
print(w_position)

# unsqueeze 해서 (4,1)로 만들기
w_position = w_position.unsqueeze(-1)

print("\n=== position weight (unsqueeze 후) ===")
print(w_position)
print("shape:", w_position.shape)

# broadcasting 곱
out2 = x * w_position

print("\n=== 결과 (x * position_weight) ===")
print(out2)


=== position weight ===
tensor([   1.,   10.,  100., 1000.])

=== position weight (unsqueeze 후) ===
tensor([[   1.],
        [  10.],
        [ 100.],
        [1000.]])
shape: torch.Size([4, 1])

=== 결과 (x * position_weight) ===
tensor([[[1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00],
         [6.0000e+01, 7.0000e+01, 8.0000e+01, 9.0000e+01, 1.0000e+02],
         [1.1000e+03, 1.2000e+03, 1.3000e+03, 1.4000e+03, 1.5000e+03],
         [1.6000e+04, 1.7000e+04, 1.8000e+04, 1.9000e+04, 2.0000e+04]]])


In [3]:
# feature + position 동시에 적용
out3 = x * w_feature
out3 = out3 * w_position

print("\n=== 최종 결과 (feature + position scaling) ===")
print(out3)


=== 최종 결과 (feature + position scaling) ===
tensor([[[1.0000e+01, 2.0000e+02, 3.0000e+03, 4.0000e+04, 5.0000e+05],
         [6.0000e+02, 7.0000e+03, 8.0000e+04, 9.0000e+05, 1.0000e+07],
         [1.1000e+04, 1.2000e+05, 1.3000e+06, 1.4000e+07, 1.5000e+08],
         [1.6000e+05, 1.7000e+06, 1.8000e+07, 1.9000e+08, 2.0000e+09]]])


In [4]:
# 실제로 확장된 형태 확인 (개념적으로)
print("\n=== feature weight 확장된 모습 (개념적) ===")
print(w_feature.view(1,1,5).expand(1,4,5))

print("\n=== position weight 확장된 모습 (개념적) ===")
print(w_position.view(1,4,1).expand(1,4,5))


=== feature weight 확장된 모습 (개념적) ===
tensor([[[1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05],
         [1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05],
         [1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05],
         [1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05]]])

=== position weight 확장된 모습 (개념적) ===
tensor([[[   1.,    1.,    1.,    1.,    1.],
         [  10.,   10.,   10.,   10.,   10.],
         [ 100.,  100.,  100.,  100.,  100.],
         [1000., 1000., 1000., 1000., 1000.]]])


# view & expand

In [5]:
# 1. 원본 벡터 확인

import torch

w = torch.tensor([10., 100., 1000., 10000., 100000.])

print("=== 원본 w ===")
print(w)
print("shape:", w.shape)

=== 원본 w ===
tensor([1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05])
shape: torch.Size([5])


In [6]:
# 2. view로 차원 바꾸기(모양만 바꿈)

w_view = w.view(1,1,5)

print("\n=== view(1,1,5) ===")
print(w_view)
print("shape:", w_view.shape)


=== view(1,1,5) ===
tensor([[[1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05]]])
shape: torch.Size([1, 1, 5])


In [7]:
# 3. expand로 늘리기(1인 차원을 "여러 개처럼 보이게"(복사 없음))

w_expand = w_view.expand(1,4,5)

print("\n=== expand(1,4,5) ===")
print(w_expand)
print("shape:", w_expand.shape)

# 1e+2 = 10² = 100


=== expand(1,4,5) ===
tensor([[[1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05],
         [1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05],
         [1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05],
         [1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05]]])
shape: torch.Size([1, 4, 5])


In [8]:
# 4. 진짜 복사인지 확인 실험

print("\n=== 메모리 공유 확인 ===")

print("원본 w 데이터 주소:", w.data_ptr())
print("expand 결과 데이터 주소:", w_expand.data_ptr())


=== 메모리 공유 확인 ===
원본 w 데이터 주소: 4353715456
expand 결과 데이터 주소: 4353715456


In [9]:
# 5. 값 바꿔보기 (핵심 실험)

print("\n=== 값 변경 실험 ===")

w[0] = 999

print("원본 w:")
print(w)

print("\nexpand 결과:")
print(w_expand)


=== 값 변경 실험 ===
원본 w:
tensor([   999.,    100.,   1000.,  10000., 100000.])

expand 결과:
tensor([[[   999.,    100.,   1000.,  10000., 100000.],
         [   999.,    100.,   1000.,  10000., 100000.],
         [   999.,    100.,   1000.,  10000., 100000.],
         [   999.,    100.,   1000.,  10000., 100000.]]])


In [10]:
# 6. expand는 직접 수정 불가능

print("\n=== expand 텐서 수정 시도 ===")

try:
    w_expand[0,1,0] = -1
except Exception as e:
    print("에러 발생:", e)


=== expand 텐서 수정 시도 ===


In [11]:
# 7. repeat와 비교 (진짜 복사해서 늘림)

w_repeat = w.view(1,1,5).repeat(1,4,1)

print("\n=== repeat 결과 ===")
print(w_repeat)
print("shape:", w_repeat.shape)

print("\n메모리 주소 비교")
print("repeat:", w_repeat.data_ptr())
print("원본:", w.data_ptr())


=== repeat 결과 ===
tensor([[[-1.0000e+00,  1.0000e+02,  1.0000e+03,  1.0000e+04,  1.0000e+05],
         [-1.0000e+00,  1.0000e+02,  1.0000e+03,  1.0000e+04,  1.0000e+05],
         [-1.0000e+00,  1.0000e+02,  1.0000e+03,  1.0000e+04,  1.0000e+05],
         [-1.0000e+00,  1.0000e+02,  1.0000e+03,  1.0000e+04,  1.0000e+05]]])
shape: torch.Size([1, 4, 5])

메모리 주소 비교
repeat: 4380986304
원본: 4353715456


In [12]:
# 8. repeat는 독립적

print("\n=== repeat 값 변경 ===")

w_repeat[0,1,0] = -999

print("repeat:")
print(w_repeat)

print("\n원본 w:")
print(w)


=== repeat 값 변경 ===
repeat:
tensor([[[-1.0000e+00,  1.0000e+02,  1.0000e+03,  1.0000e+04,  1.0000e+05],
         [-9.9900e+02,  1.0000e+02,  1.0000e+03,  1.0000e+04,  1.0000e+05],
         [-1.0000e+00,  1.0000e+02,  1.0000e+03,  1.0000e+04,  1.0000e+05],
         [-1.0000e+00,  1.0000e+02,  1.0000e+03,  1.0000e+04,  1.0000e+05]]])

원본 w:
tensor([-1.0000e+00,  1.0000e+02,  1.0000e+03,  1.0000e+04,  1.0000e+05])


In [ ]:
# 9. broadcasting 실제 적용

x = torch.arange(20.).view(1,4,5)

print("\n=== x ===")
print(x)

out = x * w

print("\n=== x * w (broadcasting) ===")
print(out)

# 시작

# 코드 옮겨써보며 외우고 복기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

class intervalModelInput(nn.Module):
    def __init__(self, d_model):
        super().__init__()
        self.feature_embedding = nn.Embedding(5, d_model)
    